WINDOW_SIZE = 640
SQUARE_SIZE = 80
PIECE_SIZE = 60

BOARD_PATH = "images/board/wood_board.png"
PIECE_PATH = "images/pieces/classic/"

PIECE_MARGIN = (WINDOW_SIZE / 8 - PIECE_SIZE) / 2
PIECE_SPACE = WINDOW_SIZE / 8

WHITE = 0
BLACK = 1